name: NodeJS Backend with Jest Coverage

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

defaults:
  run:
    working-directory: ./molecuul-backend

jobs:
  build:
    environment: Production
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
    
      - run: npm ci
      - run: npm run build --if-present
      - run: npm run pretty
      - run: npm run pretty_test
      - name: Run For Coverage
        env: 
          MONGO_USER: ${{ env.MONGO_USER }}
          MONGO_PWD: ${{ env.MONGO_PWD }}
          MONGO_CLUSTER: ${{ env.MONGO_CLUSTER }}
          MONGO_DB:  ${{ env.MONGO_DB }}
        run: npm run coverage
      
       